# Generated by Django 4.1.2 on 2022-10-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('type1', models.CharField(max_length=30)),
                ('type2', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=30)),
                ('ability', models.CharField(max_length=30)),
                ('weak', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
