# Generated by Django 4.1.2 on 2022-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_pokemons_rename_usuario_usuarios_delete_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='picture',
            field=models.CharField(max_length=400),
        ),
    ]
