# Generated by Django 4.1.2 on 2022-10-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0003_alter_pokemons_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='ability',
            new_name='debilidad',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='name',
            new_name='habilidad',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='picture',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='type1',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='type2',
            new_name='tipo1',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='weak',
            new_name='tipo2',
        ),
    ]
