# Generated by Django 4.1.1 on 2022-10-22 02:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0005_avatar_delete_usuarios_alter_pokemons_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
