# Generated by Django 4.1.2 on 2022-10-22 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pokedex', '0007_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemons',
            options={'verbose_name_plural': 'Pokemons'},
        ),
        migrations.AddField(
            model_name='pokemons',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
